 - hosts: localhost
   gather_facts: no
   become: n
   
   vars:
          image_name: "domashno2"
          image_tag: "v01"
          ports: "5002"

   tasks:
          - name: build container image and push to DockerHub
            docker_image:
               name: "{{ image_name }}"
               tag: "{{ image_tag }}"
               build:
                 path: /projects/domashno2/app
               source: build
               state: present
               repository: "mihaildanailovdimovski/domashno2:{{ image_tag }}"
               push: true

          - name: ensure a container is running
            docker_container:
               name: "{{ image_name }}"
               state: started
               image: "mihaildanailovdimovski/domashno2:{{ image_tag }}"
               pull: true
               ports:
                 - "{{ ports }}"

